/*
 * pinout_definitions.hpp
 *
 *  Created on: Sep 15, 2018
 *      Author: tamas
 */

#ifndef INC_PINOUT_DEFINITIONS_HPP_
#define INC_PINOUT_DEFINITIONS_HPP_
#include "HAL_Driver/Inc/stm32l0xx_hal.h"
// Buzzer pin definitions
#define BUZZER_TIMER_CHANNEL TIM_CHANNEL_4
#define BUZZER_TIMER TIM2
#define BUZZER_GPIO_PORT GPIOA
#define BUZZER_GPIO_PIN GPIO_PIN_3

// Display pin definitions
#define SEGMENT_NUMBER_IN_BLOCK 8
#define CONNECTED_BLOCKS 2
#define BLOCK_1_PIN_A GPIO_PIN_12
#define BLOCK_1_PIN_B GPIO_PIN_0
#define BLOCK_1_PIN_C GPIO_PIN_7
#define BLOCK_1_PIN_D GPIO_PIN_6
#define BLOCK_1_PIN_E GPIO_PIN_1
#define BLOCK_1_PIN_F GPIO_PIN_8
#define BLOCK_1_PIN_G GPIO_PIN_11
#define BLOCK_1_PIN_SP GPIO_PIN_5

#define BLOCK_1_PORT_A GPIOA
#define BLOCK_1_PORT_B GPIOB
#define BLOCK_1_PORT_C GPIOB
#define BLOCK_1_PORT_D GPIOB
#define BLOCK_1_PORT_E GPIOB
#define BLOCK_1_PORT_F GPIOA
#define BLOCK_1_PORT_G GPIOA
#define BLOCK_1_PORT_SP GPIOB

#define BLOCK_1_ENABLE_PIN GPIO_PIN_4
#define BLOCK_1_ENABLE_PORT GPIOB

#define BLOCK_2_ENABLE_PIN GPIO_PIN_4
#define BLOCK_2_ENABLE_PORT GPIOA

// Button pin definitions
#define BUTTON_1_PIN GPIO_PIN_0
#define BUTTON_2_PIN GPIO_PIN_2
#define BUTTON_1_PORT GPIOA
#define BUTTON_2_PORT GPIOA
#define BUTTON_1_ITn EXTI0_1_IRQn
#define BUTTON_2_ITn EXTI2_3_IRQn

// thermometer pin definitions
#define THERMOMETER_PIN GPIO_PIN_1
#define THERMOMETER_PORT GPIOA
#define THERMOMETER_ADC_INSTANCE ADC1
#define THERMOMETER_ADC_CHANNEL ADC_CHANNEL_1
#define THERMOMETER_REFERENCE_PIN GPIO_PIN_5
#define THERMOMETER_REFERENCE_PORT GPIOA
// BattCheck pin definitions
#define BATTCHECK_PIN GPIO_PIN_6
#define BATTCHECK_PORT GPIOA
#define BATTCHECK_ADC_INSTANCE ADC1
#define BATTCHECK_ADC_CHANNEL ADC_CHANNEL_1
#define BATTCHECK_REFERENCE_PIN GPIO_PIN_7
#define BATTCHECK_REFERENCE_PORT GPIOA
#endif  // INC_PINOUT_DEFINITIONS_HPP_
